# Generated by Django 5.0.3 on 2024-04-17 23:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mack', '0002_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPresenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20)),
                ('turma', models.CharField(max_length=50)),
                ('ano', models.CharField(max_length=10)),
                ('data', models.DateField(default=datetime.date.today)),
                ('materia', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_mack.aluno')),
            ],
        ),
    ]
